#!/usr/bin/env php
<?php

/**
 * Usage:
 *
 *   redis-dump HOST OUTPUT_FILE ["KEY_PATTERN"]
 *
 * Example:
 *
 *   redis-dump localhost localhost.dump "namespace:*"
 *
 * Options:
 *
 *   --quiet  Don't show every key that gets dumped
 *
 * @author Brandon Wamboldt <brandon.wamboldt@gmail.com>
 */
 

if (!extension_loaded('redis')) {
  echo "The Redis extension is not installed or not enabled.\n\n";
  echo "You can install the Redis extension using PECL:\n\n";
  echo "    pecl install redis\n\n";
  echo "Exiting...\n";
  exit(1);
}

if (isset($argv[3])) {
  $keys = $argv[3];
} else {
  $keys = '*';
}

// Establish connection to the redis instance we are migrating from
$dumped = 0;
$redis  = new Redis();
$redis->connect($argv[1]);
$keys = $redis->keys($keys);
$data = array();
 
foreach ($keys as $key) {
  if ($key == 'ElastiCacheMasterReplicationTimestamp') {
    continue;
  }
 
  // Get needed info about the key
  $dump = $redis->dump($key);
  $ttl  = $redis->ttl($key);
  $ttl  = $ttl == -1 ? 0 : $ttl;
 
  if (!in_array('--quiet', $argv) && !in_array('-q', $argv)) {
    echo 'Exporting key: ' . $key . " (TTL: {$ttl})\n";
  }
 
  $data[$key] = array($dump, $ttl);
}

file_put_contents($argv[2], serialize($data));
 
echo 'Successfully exported ' . count($data) . " keys\n";